services:
  nextjs:
    container_name: nextjs
    image: nextjs-rentality:latest
    ports:
      - 3000:3000
    env_file: ./docker/env.nextjs
    depends_on:
      - ganache
    networks:
      - rentality-network
    volumes:
      - ./src:/home/app/src
      - abis-volume:/home/app/src/abis
      - localnodes:/home/app/node_modules
  ganache:
    container_name: ganache
    image: ganache-rentality:latest
    ports:
      - 8545:8545
    networks:
      - rentality-network
networks:
  rentality-network:
    driver: bridge
    name: rentality-network
volumes:
  localnodes:
    driver: local
    driver_opts:
      type: none
      device: ./node_modules
      o: bind
  abis-volume:
    driver: local